//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanyalar
    {
        public int KampanyaId { get; set; }
        public string KampanyaAd { get; set; }
        public string KampanyaBanner { get; set; }
    }
}
