//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisId { get; set; }
        public Nullable<int> SiparisMusteriId { get; set; }
        public Nullable<System.DateTime> SiparisTarih { get; set; }
        public Nullable<decimal> SiparisFiyat { get; set; }
        public string Urünler { get; set; }
        public Nullable<bool> OnayDurumu { get; set; }
    }
}
